### ISSUE TITLE
Contribute Link on Top-Level README Broken

### ISSUE THREAD

**Issue by dhurlburtusa** [XcooBee/xcoobee-cookie-kit#35]
Contribute Link on Top-Level README Broken. It probably needs to link to
`https://github.com/XcooBee/xcoobee-cookie-kit/blob/master/CONTRIBUTING.md`.

Note, the README displays both on the repo's home page and the README file's page. So, relative links won't work.

**Comment by Bilal-S** [comment]
resolved
