### ISSUE TITLE
Using of ip-api.com violates our security policy

### ISSUE THREAD

**Issue by Winschu** [XcooBee/xcoobee-cookie-kit#96]
Hey,
we wanted to implement this cookie manager into our system. We wanted to display the correct language for each user so we decided to use the _detectCountry_ property in the init of the page. This was followed by a security error because of the old http protocol that was used by the api.

**Is it planned to replace this api (it seems they don't use the https protocol either)? Is it also possible to set the language manually?**

**Comment by Bilal-S** [comment]
Marcel
You can set a default country and have user select their country if different.
Use `detectCountry=false` and then
add the `defaultCountryCode` setting. You need to set it to two letter country code.

Hope this help,
Bilal

**Comment by Winschu** [comment]
Hi, thanks for the reply. We already tried this. We changed the _defaultCountryCode_ and also the _countryCode_. But the countryCode itself only changes the region that applies to the consent it does NOT change the language of the consent.

See my configuration below:
```
XcooBee.kit.initialize({
            cookieHandler: handleXCKCookies,
            checkByDefaultTypes: [],
            position: "right_bottom",
            privacyUrl: "datenschutz",
            requestDataTypes: ["statistics"],
            hideBrandTag: true,
            detectCountry: false,
            expirationTime: 0,
            termsUrl: "datenschutz",
            textMessage: {
                "de-de": "Diese Webpräsenz benutzt Cookies, um Ihnen das bestmöglichste Nutzungserlebnis zu ermöglichen.",
                "en-us": "This website uses cookies to ensure you get the best experience on our website."
            },
            countryCode: "DE",
            defaultCountryCode: "DE"
        });

**Comment by Bilal-S** [comment]
Thanks for clarifying.
I will add a ticket.

**Comment by Bilal-S** [comment]
@Winschu 
Happy New Year.
This issue should be resolved.
